### ISSUE TITLE
RedisGraph 2.0

### ISSUE THREAD

**Issue by gkorland** [mkorkmaz/redislabs-redisgraph-php#1]
Hi @mkorkmaz
Thanks for the work on this project!
We are about to release RedisGraph 2.0 officially, so I just wanted to give heads up. 
We changed our resultset structure significantly from 1.x, so the old protocol is not supported anymore.
In case you have any questions, you can reach me at our repo issues page or directly by mail.
Cheers!

**Comment by mkorkmaz** [comment]
@gkorland Thanks Guy for the warning, I will check it and update the library as soon as possible.

Best,

**Comment by mkorkmaz** [comment]
@gkorland Hi Guy,

I updated library to work with RedisGraph 2. If you have time to check it out, please do. Any comments are welcome. 

Best,
