### ISSUE TITLE
How to insert integers and other data types?

### ISSUE THREAD

**Issue by jblotus** [mkorkmaz/redislabs-redisgraph-php#2]
Hello. When I use this to insert a node, data types seem to be converted to a string.  Would it be possible to specify the type of a property when defining a node / edge ?

**Comment by mkorkmaz** [comment]
Hi @jblotus 

Actually you caught a serious bug in the library. Thanks for noticing. I will release a bugfix within hours.

**Comment by mkorkmaz** [comment]
Hi @jblotus 

I resolved the issue with the [recent commit](https://github.com/mkorkmaz/redislabs-redisgraph-php/commit/d5eeb865e139ee5169ed711d76f3d83e1ded30f5). Would you update the package and verify your case please? Thanks.

**Comment by jblotus** [comment]
This seems to work. I noticed this when trying to query for an integer value.

My use case has evolved a bit though where I want to do a MERGE instead of a CREATE since I have a lot of the same data in my set that I am iterating over so I am manually building my graph for now.

It looks something like this:
```
GRAPH.QUERY DEMO_GRAPH
"MERGE (charlie { name: 'Charlie Sheen' })
 MERGE (wallStreet:Movie { name: 'Wall Street' })
 MERGE (charlie)-[r:ACTED_IN]->(wallStreet)"
```

This is based on some advice I saw on the redisgraph documentation: https://oss.redislabs.com/redisgraph/commands/#merge

**Comment by mkorkmaz** [comment]
MERGE syntax has not been implemented in this library so far. But it seems more like CREATE syntax. Try to check this out today. I'll let you know if there will be an update. Thanks.

**Comment by mkorkmaz** [comment]
Hi @jblotus 

I introduced two methods:

- Edge::merge()
- $graph->getCommitQueryWithMerge();

I also updated README file and unit tests. This was a dirty update to understand the use case. Any comments would be appreciated. 

I'll add detailed documentation later.

**Comment by jblotus** [comment]
I will try this out today and let you know what I run into.
The use case for merge is to make sure we are not recreating nodes and/or relationships. This is somewhat similar to the mysql REPLACE INTO syntax.

There are some complexities around using MERGE and MATCH together covered in the redisgraph docs but I'm not an expert yet on all of the differences.   On interesting thing is you can specify conditional logic when something is created VS when it is getting updated.

**Comment by mkorkmaz** [comment]
In a normal manner, in this library, Node, Edge, GraphConstructor etc are actually helper classes to input formatted data and construct queries to make it easy to be used in for loops. RedisGraph is enough itself alone to operate all supported cases. When you get stuck, RedisGraph is always can be used using query method etc.

May be I should follow a complete and complex example and cover more cases like the one you mentioned above using helper classes. I am going to work on this. Thanks for your comments James.

**Comment by jblotus** [comment]
No problem at all. I think this library has some elegant structure already which is why I messed with it in the first place. 

Also I am also learning more about both graph dbs, cypher, redisgraph and am no expert but would be happy to give pull requests or feedback.
