### ISSUE TITLE
How to run unit tests?

### ISSUE THREAD

**Issue by jblotus** [mkorkmaz/redislabs-redisgraph-php#3]
Hey I'm working on a fork of the package to try and add some contributions and would like to run the unit tests.

When I do `composer run unit-tests` I get an error about a missing file `/vendor/bin/app.php`

**Comment by jblotus** [comment]
Nevermind this! I moved the project around on my filesystem after doing a composer install and several items in `vendor/bin` were missing.

**Comment by jblotus** [comment]
One thing I did have to do was ensure `XDEBUG_MODE=coverage` was set as an environment variable.  I am on php 7.4 by the way

![image](https://user-images.githubusercontent.com/382230/123810782-ae07cf80-d8c0-11eb-94ee-febd345b0464.png)

**Comment by mkorkmaz** [comment]
I use POV extension instead of XDEBUG when I am not debugging but only need to get coverage.
